### ISSUE TITLE
Project build fails with Node 13.8 for HummesJS

### ISSUE THREAD

**Issue by DroidBoyJr** [mLuby/images-to-pdf#10]
I have Node V10.15.3 on my local setup and this package worked like a charm.

While setting up on ec2 server, I installed latest stable Node V13.8 and tried to do 
`$ npm install`

Following is the log 
```> hummus@1.0.108 install /home/ubuntu/finswell-server/node_modules/hummus
> node-pre-gyp install --fallback-to-build $EXTRA_NODE_PRE_GYP_FLAGS

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://hummus.s3-us-west-2.amazonaws.com/hummus/v1.0.108/node-v79-linux-x64-glibc.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for hummus@1.0.108 and node@13.8.0 (node-v79 ABI, glibc) (falling back to source compile with node-gyp) 
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/ubuntu/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/home/ubuntu/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/home/ubuntu/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/ubuntu/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/ubuntu/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/ubuntu/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:166:21)
gyp ERR! System Linux 4.15.0-1057-aws
gyp ERR! command "/home/ubuntu/.nvm/versions/node/v13.8.0/bin/node" "/home/ubuntu/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/ubuntu/finswell-server/node_modules/hummus/binding/hummus.node" "--module_name=hummus" "--module_path=/home/ubuntu/finswell-server/node_modules/hummus/binding" "--napi_version=5" "--node_abi_napi=napi"
gyp ERR! cwd /home/ubuntu/finswell-server/node_modules/hummus
gyp ERR! node -v v13.8.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/ubuntu/.nvm/versions/node/v13.8.0/bin/node /home/ubuntu/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/ubuntu/finswell-server/node_modules/hummus/binding/hummus.node --module_name=hummus --module_path=/home/ubuntu/finswell-server/node_modules/hummus/binding --napi_version=5 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/ubuntu/finswell-server/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1026:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 4.15.0-1057-aws
node-pre-gyp ERR! command "/home/ubuntu/.nvm/versions/node/v13.8.0/bin/node" "/home/ubuntu/finswell-server/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/ubuntu/finswell-server/node_modules/hummus
node-pre-gyp ERR! node -v v13.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
Failed to execute '/home/ubuntu/.nvm/versions/node/v13.8.0/bin/node /home/ubuntu/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/ubuntu/finswell-server/node_modules/hummus/binding/hummus.node --module_name=hummus --module_path=/home/ubuntu/finswell-server/node_modules/hummus/binding --napi_version=5 --node_abi_napi=napi' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hummus@1.0.108 install: `node-pre-gyp install --fallback-to-build $EXTRA_NODE_PRE_GYP_FLAGS`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hummus@1.0.108 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-03-07T02_05_59_442Z-debug.log
```

After downgrading Node back to V10.15.3, it is now working on ec2 instance.

How do I update Node to latest and fix this?

Thank you

**Comment by mLuby** [comment]
Please try installing `hummus` directly with the target node version and let me know whether that works.

**Comment by EoinFalconer** [comment]
Hey! I'm having the same problem and hummus doesn't support node version 14.0.0. Is it possible to remove hummus from this project? :-) Thanks for the useful package!

**Comment by mLuby** [comment]
Unfortunately this is essentially a wrapper around hummus, so any limitations of that project will be blockers here as well. And you wouldn't believe how much time I spent trying to get [PDFkit](https://github.com/foliojs/pdfkit) or [PDFmake](https://github.com/bpampuch/pdfmake) to work, but 2 years ago neither was suitable for this task.

Since I don't have the bandwidth right now to re-write this package (though I welcome contributions, redirects, or transferring custodianship if someone finds a solution) it sounds like I should mark this as deprecated as of Node 14+. ☹️

**Comment by PriimeTime** [comment]
just install node 8 before running "npm install images-to-pdf --save"
